webapp/blog/models.py
import datetime
from .. import db


tags = db.Table('post_tags', 
    db.Column('post_id', db.Integer, db.ForeignKey('post.id')),
    db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'))
    )


class Post(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    title = db.Column(db.String(255))
    text = db.Column(db.Text())
    publish_date = db.Column(db.DateTime(), default=datetime.datetime.now)
    comments = db.relationship(
        'Comment',
        backref='post',
        lazy='dynamic'
    )
    user_id = db.Column(db.Integer(), db.ForeignKey('user.id'))
    tags = db.relationship(
        'Tag',
        secondary=tags,
        backref=db.backref('posts', lazy='dynamic')
    )

    def __init__(self, title=""):
        self.title = title

    def __repr__(self):
        return f"<Post '{self.title}'>'"


class Comment(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(255))
    text = db.Column(db.Text())
    date = db.Column(db.DateTime(), default=datetime.datetime.now)
    post_id = db.Column(db.Integer(), db.ForeignKey('post.id'))

    def __repr__(self):
        return f"<Comment '{self.text[:15]}'>'"


class Tag(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    title = db.Column(db.String(255), unique=True)

    def __init__(self, title=""):
        self.title = title

    def __repr__(self):
        return f"<Tag '{self.title}'>"

webapp/blog/forms.py
from flask_wtf import FlaskForm as Form
from wtforms import StringField, TextAreaField
from wtforms.validators import DataRequired, Length

class CommentForm(Form):
    name = StringField(
        'Name',
        validators=[DataRequired(), Length(max=255)]
    )
    text = TextAreaField(u'Comment', validators=[DataRequired()])


class PostForm(Form):
    title = StringField(
        'Title',
        validators=[DataRequired(), Length(max=255)]
    )
    text = TextAreaField('Content', validators=[DataRequired()])

webapp/__init__.py
from flask import Flask, render_template
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

db = SQLAlchemy()
migrate = Migrate()


def page_not_found(error):
    return render_template('404.html'), 404


def create_app(object_name):
    from .auth.controllers import auth_blueprint
    from .blog.controllers import blog_blueprint
    from .main.controllers import main_blueprint

    app = Flask(__name__)
    app.config.from_object(object_name)

    db.init_app(app)
    migrate.init_app(app, db)

    from .api import create_module as api_create_module
    from .auth import create_module as auth_create_module
    from .blog import create_module as blog_create_module
    from .main import create_module as main_create_module
    api_create_module(app)
    auth_create_module(app)
    blog_create_module(app)
    main_create_module(app)

    return app

webapp/api/__init__.py
from flask_restful import Api
from .blog.controllers import PostApi

rest_api = Api()


def create_module(app, **kwargs):
    rest_api.add_resource(
        PostApi,
        '/api/post',
        '/api/post/<int:post_id>'
    )

    rest_api.init_app(app)

webapp/api/blog/controllers.py
import datetime

from flask import abort
from flask_restful import Resource, fields, marshal_with
from flask_jwt_extended import jwt_required, get_jwt_identity
from webapp.blog.models import db, Post, Tag
from webapp.auth.models import User
from .parsers import post_get_parser
from .fields import HTMLField

nested_tag_fields = {
    'id': fields.Integer(),
    'title': fields.String()
}

post_fields = {
    'id': fields.Integer(),
    'author': fields.String(attribute=lambda x: x.user.username),
    'title': fields.String(),
    'text': HTMLField(),
    'tags': fields.List(fields.Nested(nested_tag_fields)),
    'publish_date': fields.DateTime(dt_format='iso8601')
}

class PostApi(Resource):
    @marshal_with(post_fields)
    @jwt_required
    def get(self, post_id=None):
        if post_id:
            post = Post.query.get(post_id)
            if not post:
                abort(404)
            return post
        else:
            args = post_get_parser.parse_args()
            page = args['page'] or 1
            posts = Post.query.order_by(
                Post.publish_date.desc()
            ).Paginate(page, current_app.config.get('POSTS_PER_PAGE', 10))
            return posts.items
            

webapp/blog/__init__.py
def create_module(app, **kwargs):
    from .controllers import blog_blueprint
    app.register_blueprint(blog_blueprint)

webapp/blog/controllers.py
import datetime
from sqlalchemy import func
from flask import render_template, Blueprint, flash, redirect, url_for, current_app
from flask_login import login_required, current_user
from .models import db, Post, Tag, Comment, tags

from .forms import CommentForm, PostForm
from ..auth import has_role
from ..auth.models import User


blog_blueprint = Blueprint(
    'blog',
    __name__,
    template_folder='../templates/blog',
    url_prefix="/blog"
)


def sidebar_data():
    recent = Post.query.order_by(Post.publish_date.desc()).limit(5).all()
    top_tags = db.session.query(
        Tag, func.count(tags.c.post_id).label('total')
    ).join(tags).group_by(Tag).order_by('total DESC').limit(5).all()

    return recent, top_tags


@blog_blueprint.route('/')
@blog_blueprint.route('/<int:page>')
def home(page=1):
    posts = Post.query.order_by(Post.publish_date.desc()).paginate(page, current_app.config['POSTS_PER_PAGE'])
    recent, top_tags = sidebar_data()

    return render_template(
        'home.html',
        posts=posts,
        recent=recent,
        top_tags=top_tags
    )


@blog_blueprint.route('/new', methods=['GET', 'POST'])
@login_required
@has_role('poster')
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        new_post = Post()
        new_post.user_id = current_user.id
        new_post.title = form.title.data
        new_post.text = form.text.data

        db.session.add(new_post)
        db.session.commit()
        flash("Post added", 'info')

        return redirect(url_for('blog.post', post_id=new_post.id))
    
    return render_template(
        'new.html',
        form=form
    )


@blog_blueprint.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
@has_role('poster')
def edit_post(id):
    post = Post.query.get_or_404(id)
    if current_user.id == post.user_id:
        form = PostForm()
        if form.validate_on_submit():
            post.title = form.title.data
            post.text = form.text.data
            post.publish_date = datetime.datetime.now()
            db.session.add(post)
            db.session.commit()
            return redirect(url_for('.post', post_id=post.id))
        form.title.data = post.title
        form.text.data = post.text
        return render_template(
            'edit.html',
            form=form,
            post=post
        )
    
    abort(403)


@blog_blueprint.route('/post/<int:post_id>', methods=('GET', 'POST'))
def post(post_id):
    form = CommentForm()
    if form.validate_on_submit():
        new_comment = Comment()
        new_comment.name = form.name.data
        new_comment.text = form.text.data
        new_comment.post_id = post_id
        try:
            db.session.add(new_comment)
            db.session.commit()
        except Exception as e:
            flash('Error adding your comment: %s' % str(e), 'error')
            db.session.rollback()
        else:
            flash('Comment added', 'info')
        return redirect(url_for('blog.post', post_id=post_id))

    post = Post.query.get_or_404(post_id)
    tags = post.tags
    comments = post.comments.order_by(Comment.date.desc()).all()
    recent, top_tags = sidebar_data()

    return render_template(
        'post.html',
        post=post,
        tags=tags,
        comments=comments,
        recent=recent,
        top_tags=top_tags,
        form=form
    )


@blog_blueprint.route('/posts_by_user/<string:username>')
def posts_by_user(username):
    user = User.query.filter_by(username=username).first_or_404()
    posts = user.posts.order_by(Post.publish_date.desc()).all()
    recent, top_tags = sidebar_data()
    
    return render_template(
    'user.html',
    user=user,
    posts=posts,
    recent=recent,
    top_tags=top_tags
)

@blog_blueprint.route('/posts_by_tag/<string:tag_name>')
def posts_by_tag(tag_name):
    tag = Tag.query.filter_by(title=tag_name).first_or_404() 
    posts = tag.posts.order_by(Post.publish_date.desc()).all()
    recent, top_tags = sidebar_data()

    return render_template(
        'tag.html',
        tag=tag,
        posts=posts,
        recent=recent,
        top_tags=top_tags
    )

webapp/main/__init__.py
def create_module(app, **kwargs):
    from .controllers import main_blueprint
    app.register_blueprint(main_blueprint)

webapp/main/controllers.py
from flask import Blueprint, redirect, url_for, render_template

main_blueprint = Blueprint(
    'main',
    __name__,
    template_folder='../templates/main'
)


@main_blueprint.route('/')
def index():
    return redirect(url_for('blog.home'))

webapp/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <title>{% block title %}Blog{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
        integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" 
        crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css"
        integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" 
        crossorigin="anonymous">
    </head>
    <body>
        {% include 'navbar.html' %}
        <div class="container">
            <div class="row row-lg-4">
                <div class="col">
                    {% block head %}
                    {% include 'head.html' %}
                    {% endblock %}
                </div>
            </div>
            {% include 'messages.html' %}
            {% block body %}
            <div class="row">
                <div class="col-lg-9">
                    {% block leftbody %}
                    {% endblock %}
                </div>
                <div class="col-lg-3 rounded">
                    {% block rightbody %}
                    {% include 'rightbody.html' %}
                    {% endblock %}
                </div>
            </div>
            {% endblock %}
            {% include 'footer.html' %}
        </div>
    </body>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" 
    integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
    crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" 
    integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" 
    crossorigin="anonymous"></script>
</html>

webapp/templates/footer.html
Brett 2019

webapp/templates/generic_list.html
{% extends 'base.html' %}
{% block body %}

<div class="table-responsive">
    <table class="table table-bordered table-hover">
        {% for obj in objects %}
            <tr>
                {% for col in columns %}
                <td>
                    {{ col }} {{ obj[col] }}
                </td>
                {% endfor %}
            </tr>
        {% endfor %}
    </table>
</div>

{% endblock %}

webapp/templates/head.html
<div class="container bg-info rounded">
    <center>
        <i class="fas fa-comments fa-5x"></i>
        <h1><a class="text-white" href="{{ url_for('blog.home') }}">My Blog</a></h1>
        <p>Welcome to the blog!</p>
    </center>
</div>

webapp/templates/macros.html
{% macro render_pagination(pagination, endpoint) %}
<nav aria-label="Page navigation example">
    <ul class="pagination">
        {% if pagination.has_prev %}
        <li class="page-item">
            <a class="page-link" href="{{ url_for('blog.home', page=pagination.prev().page)}}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a> 
        </li>
        {% endif %}
        {% for page in pagination.iter_pages() %}
            {% if page %}
                {% if page != pagination.page %}
                    <li class="page-item">
                        <a class="page-link" href="{{ url_for(endpoint, page=page) }}">{{ page }}</a>
                    </li>
                {% else %}
                    <li class="page-item active">
                        <a class="page-link" href="">{{ page }}</a>
                    </li>
                {% endif %}
            {% else %}
                <li class="page-item">
                    <a class="page-link">...</a>
                </li>
            {% endif %}
        {% endfor %}
        {% if pagination.has_next %}
            <li class="page-item">
                <a class="page-link" href="{{ url_for('blog.home', page=pagination.next().page) }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Next</span>
                </a>
            </li>
        {% endif %}
    </ul>
</nav>
{% endmacro %}


{% macro render_posts(posts, pagination=True) %}
{% if pagination %}
    {% set _posts = posts.items %}
{% else %}
    {% set _posts = posts %}
{% endif %}
{% for post in _posts %}
<div>
    <h1>
        <a class="text-dark" href={{ url_for('blog.post', post_id=post.id) }}>{{ post.title }}</a>
    </h1>
</div>
<div class="row">
    <div class="col">
        {{ post.text | truncate(500) | safe }}
        <a href="{{ url_for('blog.post', post_id=post.id) }}">Read More</a>
    </div>
</div>
{% endfor %}
{% endmacro %}

webapp/templates/messages.html
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
{% for category, message in messages %}
<div class="alert alert-{{ category }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    {{ message }}
</div>
{% endfor %}
{% endif %}
{% endwith %}

webapp/templates/navbar.html
<div class="container">
    <div class="row row-lg-4">
        <div class="col">
            <center>
                <nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="color: black;">
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item active">
                                <a class="nav-link" href="{{url_for('blog.home')}}">Home <span class="sr-only">(current)</span></a>
                            </li>
                            {% if current_user.is_authenticated and current_user.has_role('poster') %}
                            <li class="nav-item">
                                <a class="nav-link" href="{{url_for('blog.new_post')}}">New Post<span class="sr-only">(current)</span></a>
                            </li>
                            {% endif %}
                        </ul>
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="{{url_for('blog.home')}}"></a>
                            </li>
                            {% if current_user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="#user">
                                    <i class="fa fa-fw fa-sign-out"></i>{{ current_user.username }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{url_for('auth.logout')}}">
                                <i class="fa fa-fw fa-sign-out"></i>Logout</a>
                            </li>

                            {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{{url_for('auth.login')}}">
                                <i class="fa fa-fw fa-sign-in"></i>Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{url_for('auth.register')}}">
                                <i class="fa fa-fw fa-sign-in"></i>Register</a>
                            </li>
                            {% endif %}
                        </ul>
                    </div>
                </nav>
            </center>
        </div>
    </div>
</div>